name: TODO Workflow

on: ["push", "pull_request", "workflow_dispatch"]

jobs:
  todo-pipeline:
    runs-on: ubuntu-latest
    steps:
    # add needed steps here
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12
    - name: Install dependencies
      run: make pipeline
